server:
  port: 8089
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/yun6?serverTimezone=GMT%2B8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    ip-address: 127.0.0.1
    prefer-ip-address: true
mybatis:
  type-aliases-package: com.leyou.order.pojo
ly:
  jwt:
    pubKeyPath: D:/app/yun6/rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  worker:
    workerId: 1
    dataCenterId: 1
  pay:
    appID: wx8933434243
    mchID: 32443443
    key: T5309fsdf
    httpConnectTimeoutMs: 1000
    httpReadTimeoutMs: 8000
    notifyUrl: http://a3gjdfoj.com/notify